/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.AlwaysAllowedPermission;
import com.delphix.dct.models.ScopeTag;
import com.delphix.dct.models.ScopedObjectItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AccessGroupScope
 */
public class AccessGroupScopeTest {
    private final AccessGroupScope model = new AccessGroupScope();

    /**
     * Model tests for AccessGroupScope
     */
    @Test
    public void testAccessGroupScope() {
        // TODO: test AccessGroupScope
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'roleId'
     */
    @Test
    public void roleIdTest() {
        // TODO: test roleId
    }

    /**
     * Test the property 'scopeType'
     */
    @Test
    public void scopeTypeTest() {
        // TODO: test scopeType
    }

    /**
     * Test the property 'objectTags'
     */
    @Test
    public void objectTagsTest() {
        // TODO: test objectTags
    }

    /**
     * Test the property 'objects'
     */
    @Test
    public void objectsTest() {
        // TODO: test objects
    }

    /**
     * Test the property 'alwaysAllowedPermissions'
     */
    @Test
    public void alwaysAllowedPermissionsTest() {
        // TODO: test alwaysAllowedPermissions
    }

}
