/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.AlwaysAllowedPermission;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AlwaysAllowedPermissionRequest
 */
public class AlwaysAllowedPermissionRequestTest {
    private final AlwaysAllowedPermissionRequest model = new AlwaysAllowedPermissionRequest();

    /**
     * Model tests for AlwaysAllowedPermissionRequest
     */
    @Test
    public void testAlwaysAllowedPermissionRequest() {
        // TODO: test AlwaysAllowedPermissionRequest
    }

    /**
     * Test the property 'alwaysAllowedPermissions'
     */
    @Test
    public void alwaysAllowedPermissionsTest() {
        // TODO: test alwaysAllowedPermissions
    }

}
