/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConnectivityCheckParameters
 */
public class ConnectivityCheckParametersTest {
    private final ConnectivityCheckParameters model = new ConnectivityCheckParameters();

    /**
     * Model tests for ConnectivityCheckParameters
     */
    @Test
    public void testConnectivityCheckParameters() {
        // TODO: test ConnectivityCheckParameters
    }

    /**
     * Test the property 'engineId'
     */
    @Test
    public void engineIdTest() {
        // TODO: test engineId
    }

    /**
     * Test the property 'useEnginePublicKey'
     */
    @Test
    public void useEnginePublicKeyTest() {
        // TODO: test useEnginePublicKey
    }

    /**
     * Test the property 'osName'
     */
    @Test
    public void osNameTest() {
        // TODO: test osName
    }

    /**
     * Test the property 'stagingEnvironment'
     */
    @Test
    public void stagingEnvironmentTest() {
        // TODO: test stagingEnvironment
    }

    /**
     * Test the property 'host'
     */
    @Test
    public void hostTest() {
        // TODO: test host
    }

    /**
     * Test the property 'port'
     */
    @Test
    public void portTest() {
        // TODO: test port
    }

    /**
     * Test the property 'username'
     */
    @Test
    public void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

}
