/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PaginatedResponseMetadata
 */
public class PaginatedResponseMetadataTest {
    private final PaginatedResponseMetadata model = new PaginatedResponseMetadata();

    /**
     * Model tests for PaginatedResponseMetadata
     */
    @Test
    public void testPaginatedResponseMetadata() {
        // TODO: test PaginatedResponseMetadata
    }

    /**
     * Test the property 'prevCursor'
     */
    @Test
    public void prevCursorTest() {
        // TODO: test prevCursor
    }

    /**
     * Test the property 'nextCursor'
     */
    @Test
    public void nextCursorTest() {
        // TODO: test nextCursor
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
