/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.AdditionalMountPoint;
import com.delphix.dct.models.OracleRacCustomEnvFile;
import com.delphix.dct.models.OracleRacCustomEnvVar;
import com.delphix.dct.models.VirtualDatasetHooks;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UpdateVDBParameters
 */
public class UpdateVDBParametersTest {
    private final UpdateVDBParameters model = new UpdateVDBParameters();

    /**
     * Model tests for UpdateVDBParameters
     */
    @Test
    public void testUpdateVDBParameters() {
        // TODO: test UpdateVDBParameters
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'dbUsername'
     */
    @Test
    public void dbUsernameTest() {
        // TODO: test dbUsername
    }

    /**
     * Test the property 'dbPassword'
     */
    @Test
    public void dbPasswordTest() {
        // TODO: test dbPassword
    }

    /**
     * Test the property 'validateDbCredentials'
     */
    @Test
    public void validateDbCredentialsTest() {
        // TODO: test validateDbCredentials
    }

    /**
     * Test the property 'autoRestart'
     */
    @Test
    public void autoRestartTest() {
        // TODO: test autoRestart
    }

    /**
     * Test the property 'environmentUserId'
     */
    @Test
    public void environmentUserIdTest() {
        // TODO: test environmentUserId
    }

    /**
     * Test the property 'templateId'
     */
    @Test
    public void templateIdTest() {
        // TODO: test templateId
    }

    /**
     * Test the property 'listenerIds'
     */
    @Test
    public void listenerIdsTest() {
        // TODO: test listenerIds
    }

    /**
     * Test the property 'newDbid'
     */
    @Test
    public void newDbidTest() {
        // TODO: test newDbid
    }

    /**
     * Test the property 'cdcOnProvision'
     */
    @Test
    public void cdcOnProvisionTest() {
        // TODO: test cdcOnProvision
    }

    /**
     * Test the property 'preScript'
     */
    @Test
    public void preScriptTest() {
        // TODO: test preScript
    }

    /**
     * Test the property 'postScript'
     */
    @Test
    public void postScriptTest() {
        // TODO: test postScript
    }

    /**
     * Test the property 'hooks'
     */
    @Test
    public void hooksTest() {
        // TODO: test hooks
    }

    /**
     * Test the property 'customEnvVars'
     */
    @Test
    public void customEnvVarsTest() {
        // TODO: test customEnvVars
    }

    /**
     * Test the property 'customEnvFiles'
     */
    @Test
    public void customEnvFilesTest() {
        // TODO: test customEnvFiles
    }

    /**
     * Test the property 'oracleRacCustomEnvFiles'
     */
    @Test
    public void oracleRacCustomEnvFilesTest() {
        // TODO: test oracleRacCustomEnvFiles
    }

    /**
     * Test the property 'oracleRacCustomEnvVars'
     */
    @Test
    public void oracleRacCustomEnvVarsTest() {
        // TODO: test oracleRacCustomEnvVars
    }

    /**
     * Test the property 'parentTdeKeystorePath'
     */
    @Test
    public void parentTdeKeystorePathTest() {
        // TODO: test parentTdeKeystorePath
    }

    /**
     * Test the property 'parentTdeKeystorePassword'
     */
    @Test
    public void parentTdeKeystorePasswordTest() {
        // TODO: test parentTdeKeystorePassword
    }

    /**
     * Test the property 'tdeKeyIdentifier'
     */
    @Test
    public void tdeKeyIdentifierTest() {
        // TODO: test tdeKeyIdentifier
    }

    /**
     * Test the property 'targetVcdbTdeKeystorePath'
     */
    @Test
    public void targetVcdbTdeKeystorePathTest() {
        // TODO: test targetVcdbTdeKeystorePath
    }

    /**
     * Test the property 'cdbTdeKeystorePassword'
     */
    @Test
    public void cdbTdeKeystorePasswordTest() {
        // TODO: test cdbTdeKeystorePassword
    }

    /**
     * Test the property 'appdataSourceParams'
     */
    @Test
    public void appdataSourceParamsTest() {
        // TODO: test appdataSourceParams
    }

    /**
     * Test the property 'additionalMountPoints'
     */
    @Test
    public void additionalMountPointsTest() {
        // TODO: test additionalMountPoints
    }

    /**
     * Test the property 'appdataConfigParams'
     */
    @Test
    public void appdataConfigParamsTest() {
        // TODO: test appdataConfigParams
    }

    /**
     * Test the property 'configParams'
     */
    @Test
    public void configParamsTest() {
        // TODO: test configParams
    }

    /**
     * Test the property 'mountPoint'
     */
    @Test
    public void mountPointTest() {
        // TODO: test mountPoint
    }

}
