/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BundleUploadEvent
 */
public class BundleUploadEventTest {
    private final BundleUploadEvent model = new BundleUploadEvent();

    /**
     * Model tests for BundleUploadEvent
     */
    @Test
    public void testBundleUploadEvent() {
        // TODO: test BundleUploadEvent
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'generationStartTime'
     */
    @Test
    public void generationStartTimeTest() {
        // TODO: test generationStartTime
    }

    /**
     * Test the property 'generationEndTime'
     */
    @Test
    public void generationEndTimeTest() {
        // TODO: test generationEndTime
    }

    /**
     * Test the property 'allGapsFilled'
     */
    @Test
    public void allGapsFilledTest() {
        // TODO: test allGapsFilled
    }

    /**
     * Test the property 'dataDates'
     */
    @Test
    public void dataDatesTest() {
        // TODO: test dataDates
    }

}
