/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Host;
import com.delphix.dct.models.OracleListener;
import com.delphix.dct.models.Repository;
import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Environment
 */
public class EnvironmentTest {
    private final Environment model = new Environment();

    /**
     * Model tests for Environment
     */
    @Test
    public void testEnvironment() {
        // TODO: test Environment
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespaceId'
     */
    @Test
    public void namespaceIdTest() {
        // TODO: test namespaceId
    }

    /**
     * Test the property 'namespaceName'
     */
    @Test
    public void namespaceNameTest() {
        // TODO: test namespaceName
    }

    /**
     * Test the property 'isReplica'
     */
    @Test
    public void isReplicaTest() {
        // TODO: test isReplica
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'engineId'
     */
    @Test
    public void engineIdTest() {
        // TODO: test engineId
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'isCluster'
     */
    @Test
    public void isClusterTest() {
        // TODO: test isCluster
    }

    /**
     * Test the property 'clusterHome'
     */
    @Test
    public void clusterHomeTest() {
        // TODO: test clusterHome
    }

    /**
     * Test the property 'isWindowsTarget'
     */
    @Test
    public void isWindowsTargetTest() {
        // TODO: test isWindowsTarget
    }

    /**
     * Test the property 'stagingEnvironment'
     */
    @Test
    public void stagingEnvironmentTest() {
        // TODO: test stagingEnvironment
    }

    /**
     * Test the property 'hosts'
     */
    @Test
    public void hostsTest() {
        // TODO: test hosts
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'repositories'
     */
    @Test
    public void repositoriesTest() {
        // TODO: test repositories
    }

    /**
     * Test the property 'listeners'
     */
    @Test
    public void listenersTest() {
        // TODO: test listeners
    }

}
