/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GlobalProperties
 */
public class GlobalPropertiesTest {
    private final GlobalProperties model = new GlobalProperties();

    /**
     * Model tests for GlobalProperties
     */
    @Test
    public void testGlobalProperties() {
        // TODO: test GlobalProperties
    }

    /**
     * Test the property 'disableUsernamePassword'
     */
    @Test
    public void disableUsernamePasswordTest() {
        // TODO: test disableUsernamePassword
    }

    /**
     * Test the property 'phonehomeUploadCadence'
     */
    @Test
    public void phonehomeUploadCadenceTest() {
        // TODO: test phonehomeUploadCadence
    }

    /**
     * Test the property 'phonehomeMaximumTransferSize'
     */
    @Test
    public void phonehomeMaximumTransferSizeTest() {
        // TODO: test phonehomeMaximumTransferSize
    }

}
