/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Engine;
import com.delphix.dct.models.Tag;
import com.delphix.dct.models.VirtualizationTask;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Job
 */
public class JobTest {
    private final Job model = new Job();

    /**
     * Model tests for Job
     */
    @Test
    public void testJob() {
        // TODO: test Job
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'isWaitingForTelemetry'
     */
    @Test
    public void isWaitingForTelemetryTest() {
        // TODO: test isWaitingForTelemetry
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'localizedType'
     */
    @Test
    public void localizedTypeTest() {
        // TODO: test localizedType
    }

    /**
     * Test the property 'errorDetails'
     */
    @Test
    public void errorDetailsTest() {
        // TODO: test errorDetails
    }

    /**
     * Test the property 'warningMessage'
     */
    @Test
    public void warningMessageTest() {
        // TODO: test warningMessage
    }

    /**
     * Test the property 'targetId'
     */
    @Test
    public void targetIdTest() {
        // TODO: test targetId
    }

    /**
     * Test the property 'targetName'
     */
    @Test
    public void targetNameTest() {
        // TODO: test targetName
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'updateTime'
     */
    @Test
    public void updateTimeTest() {
        // TODO: test updateTime
    }

    /**
     * Test the property 'traceId'
     */
    @Test
    public void traceIdTest() {
        // TODO: test traceId
    }

    /**
     * Test the property 'engineIds'
     */
    @Test
    public void engineIdsTest() {
        // TODO: test engineIds
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'engines'
     */
    @Test
    public void enginesTest() {
        // TODO: test engines
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'accountName'
     */
    @Test
    public void accountNameTest() {
        // TODO: test accountName
    }

    /**
     * Test the property 'percentComplete'
     */
    @Test
    public void percentCompleteTest() {
        // TODO: test percentComplete
    }

    /**
     * Test the property 'virtualizationTasks'
     */
    @Test
    public void virtualizationTasksTest() {
        // TODO: test virtualizationTasks
    }

}
