/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Connector;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MaskingJobConnectorsResponse
 */
public class MaskingJobConnectorsResponseTest {
    private final MaskingJobConnectorsResponse model = new MaskingJobConnectorsResponse();

    /**
     * Model tests for MaskingJobConnectorsResponse
     */
    @Test
    public void testMaskingJobConnectorsResponse() {
        // TODO: test MaskingJobConnectorsResponse
    }

    /**
     * Test the property 'connector'
     */
    @Test
    public void connectorTest() {
        // TODO: test connector
    }

    /**
     * Test the property 'onTheFlyConnector'
     */
    @Test
    public void onTheFlyConnectorTest() {
        // TODO: test onTheFlyConnector
    }

}
