/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import com.delphix.dct.models.Tag;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Source
 */
public class SourceTest {
    private final Source model = new Source();

    /**
     * Model tests for Source
     */
    @Test
    public void testSource() {
        // TODO: test Source
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'databaseType'
     */
    @Test
    public void databaseTypeTest() {
        // TODO: test databaseType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespaceId'
     */
    @Test
    public void namespaceIdTest() {
        // TODO: test namespaceId
    }

    /**
     * Test the property 'namespaceName'
     */
    @Test
    public void namespaceNameTest() {
        // TODO: test namespaceName
    }

    /**
     * Test the property 'isReplica'
     */
    @Test
    public void isReplicaTest() {
        // TODO: test isReplica
    }

    /**
     * Test the property 'databaseVersion'
     */
    @Test
    public void databaseVersionTest() {
        // TODO: test databaseVersion
    }

    /**
     * Test the property 'environmentId'
     */
    @Test
    public void environmentIdTest() {
        // TODO: test environmentId
    }

    /**
     * Test the property 'dataUuid'
     */
    @Test
    public void dataUuidTest() {
        // TODO: test dataUuid
    }

    /**
     * Test the property 'ipAddress'
     */
    @Test
    public void ipAddressTest() {
        // TODO: test ipAddress
    }

    /**
     * Test the property 'fqdn'
     */
    @Test
    public void fqdnTest() {
        // TODO: test fqdn
    }

    /**
     * Test the property 'size'
     */
    @Test
    public void sizeTest() {
        // TODO: test size
    }

    /**
     * Test the property 'jdbcConnectionString'
     */
    @Test
    public void jdbcConnectionStringTest() {
        // TODO: test jdbcConnectionString
    }

    /**
     * Test the property 'pluginVersion'
     */
    @Test
    public void pluginVersionTest() {
        // TODO: test pluginVersion
    }

    /**
     * Test the property 'toolkitId'
     */
    @Test
    public void toolkitIdTest() {
        // TODO: test toolkitId
    }

    /**
     * Test the property 'isDsource'
     */
    @Test
    public void isDsourceTest() {
        // TODO: test isDsource
    }

    /**
     * Test the property 'repository'
     */
    @Test
    public void repositoryTest() {
        // TODO: test repository
    }

    /**
     * Test the property 'recoveryModel'
     */
    @Test
    public void recoveryModelTest() {
        // TODO: test recoveryModel
    }

    /**
     * Test the property 'mssqlSourceType'
     */
    @Test
    public void mssqlSourceTypeTest() {
        // TODO: test mssqlSourceType
    }

    /**
     * Test the property 'appdataSourceType'
     */
    @Test
    public void appdataSourceTypeTest() {
        // TODO: test appdataSourceType
    }

    /**
     * Test the property 'isPdb'
     */
    @Test
    public void isPdbTest() {
        // TODO: test isPdb
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

}
