/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.delphix.dct.JSON;

/**
 * VDB id and name associated with bookmark.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-03T12:02:33.321319+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
public class BookmarkVDBs {
  public static final String SERIALIZED_NAME_VDB_ID = "vdb_id";
  @SerializedName(SERIALIZED_NAME_VDB_ID)
  private String vdbId;

  public static final String SERIALIZED_NAME_VDB_NAME = "vdb_name";
  @SerializedName(SERIALIZED_NAME_VDB_NAME)
  private String vdbName;

  public BookmarkVDBs() {
  }

  public BookmarkVDBs vdbId(String vdbId) {
    this.vdbId = vdbId;
    return this;
  }

   /**
   * The VDB id.
   * @return vdbId
  **/
  @javax.annotation.Nullable
  public String getVdbId() {
    return vdbId;
  }

  public void setVdbId(String vdbId) {
    this.vdbId = vdbId;
  }


  public BookmarkVDBs vdbName(String vdbName) {
    this.vdbName = vdbName;
    return this;
  }

   /**
   * The VDB name.
   * @return vdbName
  **/
  @javax.annotation.Nullable
  public String getVdbName() {
    return vdbName;
  }

  public void setVdbName(String vdbName) {
    this.vdbName = vdbName;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BookmarkVDBs bookmarkVDBs = (BookmarkVDBs) o;
    return Objects.equals(this.vdbId, bookmarkVDBs.vdbId) &&
        Objects.equals(this.vdbName, bookmarkVDBs.vdbName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vdbId, vdbName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BookmarkVDBs {\n");
    sb.append("    vdbId: ").append(toIndentedString(vdbId)).append("\n");
    sb.append("    vdbName: ").append(toIndentedString(vdbName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("vdb_id");
    openapiFields.add("vdb_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to BookmarkVDBs
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BookmarkVDBs.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BookmarkVDBs is not found in the empty JSON string", BookmarkVDBs.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BookmarkVDBs.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BookmarkVDBs` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("vdb_id") != null && !jsonObj.get("vdb_id").isJsonNull()) && !jsonObj.get("vdb_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vdb_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vdb_id").toString()));
      }
      if ((jsonObj.get("vdb_name") != null && !jsonObj.get("vdb_name").isJsonNull()) && !jsonObj.get("vdb_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `vdb_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("vdb_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BookmarkVDBs.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BookmarkVDBs' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BookmarkVDBs> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BookmarkVDBs.class));

       return (TypeAdapter<T>) new TypeAdapter<BookmarkVDBs>() {
           @Override
           public void write(JsonWriter out, BookmarkVDBs value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BookmarkVDBs read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of BookmarkVDBs given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of BookmarkVDBs
  * @throws IOException if the JSON string is invalid with respect to BookmarkVDBs
  */
  public static BookmarkVDBs fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BookmarkVDBs.class);
  }

 /**
  * Convert an instance of BookmarkVDBs to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

