/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.delphix.dct.JSON;

/**
 * OracleListener
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-04T14:49:34.152994+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
public class OracleListener {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * Type of this listener.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    NODE("NODE"),
    
    SCAN("SCAN");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      TypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_PROTOCOL_ADDRESSES = "protocol_addresses";
  @SerializedName(SERIALIZED_NAME_PROTOCOL_ADDRESSES)
  private List<String> protocolAddresses;

  public static final String SERIALIZED_NAME_CLIENT_ENDPOINTS = "client_endpoints";
  @SerializedName(SERIALIZED_NAME_CLIENT_ENDPOINTS)
  private List<String> clientEndpoints;

  public static final String SERIALIZED_NAME_IS_DISCOVERED = "is_discovered";
  @SerializedName(SERIALIZED_NAME_IS_DISCOVERED)
  private Boolean isDiscovered;

  public static final String SERIALIZED_NAME_HOST_ID = "host_id";
  @SerializedName(SERIALIZED_NAME_HOST_ID)
  private String hostId;

  public OracleListener() {
  }

  public OracleListener id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Id of this listener.
   * @return id
  **/
  @javax.annotation.Nullable
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  public OracleListener name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of this listener.
   * @return name
  **/
  @javax.annotation.Nullable
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  public OracleListener type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type of this listener.
   * @return type
  **/
  @javax.annotation.Nullable
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  public OracleListener protocolAddresses(List<String> protocolAddresses) {
    this.protocolAddresses = protocolAddresses;
    return this;
  }

  public OracleListener addProtocolAddressesItem(String protocolAddressesItem) {
    if (this.protocolAddresses == null) {
      this.protocolAddresses = new ArrayList<>();
    }
    this.protocolAddresses.add(protocolAddressesItem);
    return this;
  }

   /**
   * The list of protocol addresses for this listener.
   * @return protocolAddresses
  **/
  @javax.annotation.Nullable
  public List<String> getProtocolAddresses() {
    return protocolAddresses;
  }

  public void setProtocolAddresses(List<String> protocolAddresses) {
    this.protocolAddresses = protocolAddresses;
  }


  public OracleListener clientEndpoints(List<String> clientEndpoints) {
    this.clientEndpoints = clientEndpoints;
    return this;
  }

  public OracleListener addClientEndpointsItem(String clientEndpointsItem) {
    if (this.clientEndpoints == null) {
      this.clientEndpoints = new ArrayList<>();
    }
    this.clientEndpoints.add(clientEndpointsItem);
    return this;
  }

   /**
   * The list of client endpoints for this listener.
   * @return clientEndpoints
  **/
  @javax.annotation.Nullable
  public List<String> getClientEndpoints() {
    return clientEndpoints;
  }

  public void setClientEndpoints(List<String> clientEndpoints) {
    this.clientEndpoints = clientEndpoints;
  }


  public OracleListener isDiscovered(Boolean isDiscovered) {
    this.isDiscovered = isDiscovered;
    return this;
  }

   /**
   * Whether this listener was automatically discovered or not.
   * @return isDiscovered
  **/
  @javax.annotation.Nullable
  public Boolean getIsDiscovered() {
    return isDiscovered;
  }

  public void setIsDiscovered(Boolean isDiscovered) {
    this.isDiscovered = isDiscovered;
  }


  public OracleListener hostId(String hostId) {
    this.hostId = hostId;
    return this;
  }

   /**
   * Id to the host this listener is associated with.
   * @return hostId
  **/
  @javax.annotation.Nullable
  public String getHostId() {
    return hostId;
  }

  public void setHostId(String hostId) {
    this.hostId = hostId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OracleListener oracleListener = (OracleListener) o;
    return Objects.equals(this.id, oracleListener.id) &&
        Objects.equals(this.name, oracleListener.name) &&
        Objects.equals(this.type, oracleListener.type) &&
        Objects.equals(this.protocolAddresses, oracleListener.protocolAddresses) &&
        Objects.equals(this.clientEndpoints, oracleListener.clientEndpoints) &&
        Objects.equals(this.isDiscovered, oracleListener.isDiscovered) &&
        Objects.equals(this.hostId, oracleListener.hostId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, protocolAddresses, clientEndpoints, isDiscovered, hostId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OracleListener {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    protocolAddresses: ").append(toIndentedString(protocolAddresses)).append("\n");
    sb.append("    clientEndpoints: ").append(toIndentedString(clientEndpoints)).append("\n");
    sb.append("    isDiscovered: ").append(toIndentedString(isDiscovered)).append("\n");
    sb.append("    hostId: ").append(toIndentedString(hostId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("name");
    openapiFields.add("type");
    openapiFields.add("protocol_addresses");
    openapiFields.add("client_endpoints");
    openapiFields.add("is_discovered");
    openapiFields.add("host_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to OracleListener
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OracleListener.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OracleListener is not found in the empty JSON string", OracleListener.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OracleListener.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OracleListener` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        TypeEnum.validateJsonElement(jsonObj.get("type"));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("protocol_addresses") != null && !jsonObj.get("protocol_addresses").isJsonNull() && !jsonObj.get("protocol_addresses").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `protocol_addresses` to be an array in the JSON string but got `%s`", jsonObj.get("protocol_addresses").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("client_endpoints") != null && !jsonObj.get("client_endpoints").isJsonNull() && !jsonObj.get("client_endpoints").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `client_endpoints` to be an array in the JSON string but got `%s`", jsonObj.get("client_endpoints").toString()));
      }
      if ((jsonObj.get("host_id") != null && !jsonObj.get("host_id").isJsonNull()) && !jsonObj.get("host_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `host_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("host_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OracleListener.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OracleListener' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OracleListener> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OracleListener.class));

       return (TypeAdapter<T>) new TypeAdapter<OracleListener>() {
           @Override
           public void write(JsonWriter out, OracleListener value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OracleListener read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of OracleListener given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of OracleListener
  * @throws IOException if the JSON string is invalid with respect to OracleListener
  */
  public static OracleListener fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OracleListener.class);
  }

 /**
  * Convert an instance of OracleListener to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

