/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.delphix.dct.JSON;

/**
 * Product registration object for a manually generated payload.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-04T14:49:34.152994+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
public class ProductRegistrationOfflinePayload {
  public static final String SERIALIZED_NAME_DATA_KEY = "data_key";
  @SerializedName(SERIALIZED_NAME_DATA_KEY)
  private String dataKey;

  public static final String SERIALIZED_NAME_AUTHENTICATION_TOKEN = "authentication_token";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_TOKEN)
  private String authenticationToken;

  public ProductRegistrationOfflinePayload() {
  }

  public ProductRegistrationOfflinePayload dataKey(String dataKey) {
    this.dataKey = dataKey;
    return this;
  }

   /**
   * Get dataKey
   * @return dataKey
  **/
  @javax.annotation.Nonnull
  public String getDataKey() {
    return dataKey;
  }

  public void setDataKey(String dataKey) {
    this.dataKey = dataKey;
  }


  public ProductRegistrationOfflinePayload authenticationToken(String authenticationToken) {
    this.authenticationToken = authenticationToken;
    return this;
  }

   /**
   * Get authenticationToken
   * @return authenticationToken
  **/
  @javax.annotation.Nonnull
  public String getAuthenticationToken() {
    return authenticationToken;
  }

  public void setAuthenticationToken(String authenticationToken) {
    this.authenticationToken = authenticationToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductRegistrationOfflinePayload productRegistrationOfflinePayload = (ProductRegistrationOfflinePayload) o;
    return Objects.equals(this.dataKey, productRegistrationOfflinePayload.dataKey) &&
        Objects.equals(this.authenticationToken, productRegistrationOfflinePayload.authenticationToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dataKey, authenticationToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductRegistrationOfflinePayload {\n");
    sb.append("    dataKey: ").append(toIndentedString(dataKey)).append("\n");
    sb.append("    authenticationToken: ").append(toIndentedString(authenticationToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("data_key");
    openapiFields.add("authentication_token");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("data_key");
    openapiRequiredFields.add("authentication_token");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProductRegistrationOfflinePayload
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProductRegistrationOfflinePayload.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProductRegistrationOfflinePayload is not found in the empty JSON string", ProductRegistrationOfflinePayload.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProductRegistrationOfflinePayload.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProductRegistrationOfflinePayload` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ProductRegistrationOfflinePayload.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (!jsonObj.get("data_key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `data_key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("data_key").toString()));
      }
      if (!jsonObj.get("authentication_token").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `authentication_token` to be a primitive type in the JSON string but got `%s`", jsonObj.get("authentication_token").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProductRegistrationOfflinePayload.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProductRegistrationOfflinePayload' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProductRegistrationOfflinePayload> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProductRegistrationOfflinePayload.class));

       return (TypeAdapter<T>) new TypeAdapter<ProductRegistrationOfflinePayload>() {
           @Override
           public void write(JsonWriter out, ProductRegistrationOfflinePayload value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProductRegistrationOfflinePayload read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProductRegistrationOfflinePayload given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProductRegistrationOfflinePayload
  * @throws IOException if the JSON string is invalid with respect to ProductRegistrationOfflinePayload
  */
  public static ProductRegistrationOfflinePayload fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProductRegistrationOfflinePayload.class);
  }

 /**
  * Convert an instance of ProductRegistrationOfflinePayload to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

