/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.10.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.delphix.dct.JSON;

/**
 * ProvisionVDBBySnapshotDefaultsRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-04T14:49:34.152994+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
public class ProvisionVDBBySnapshotDefaultsRequest {
  public static final String SERIALIZED_NAME_SNAPSHOT_ID = "snapshot_id";
  @SerializedName(SERIALIZED_NAME_SNAPSHOT_ID)
  private String snapshotId;

  public static final String SERIALIZED_NAME_ENGINE_ID = "engine_id";
  @SerializedName(SERIALIZED_NAME_ENGINE_ID)
  private String engineId;

  public static final String SERIALIZED_NAME_SOURCE_DATA_ID = "source_data_id";
  @SerializedName(SERIALIZED_NAME_SOURCE_DATA_ID)
  private String sourceDataId;

  public ProvisionVDBBySnapshotDefaultsRequest() {
  }

  public ProvisionVDBBySnapshotDefaultsRequest snapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
    return this;
  }

   /**
   * The ID of the snapshot from which to execute the operation.
   * @return snapshotId
  **/
  @javax.annotation.Nullable
  public String getSnapshotId() {
    return snapshotId;
  }

  public void setSnapshotId(String snapshotId) {
    this.snapshotId = snapshotId;
  }


  public ProvisionVDBBySnapshotDefaultsRequest engineId(String engineId) {
    this.engineId = engineId;
    return this;
  }

   /**
   * The ID of the Engine onto which to provision. If the source ID unambiguously identifies a source object, this parameter is unnecessary and ignored.
   * @return engineId
  **/
  @javax.annotation.Nullable
  public String getEngineId() {
    return engineId;
  }

  public void setEngineId(String engineId) {
    this.engineId = engineId;
  }


  public ProvisionVDBBySnapshotDefaultsRequest sourceDataId(String sourceDataId) {
    this.sourceDataId = sourceDataId;
    return this;
  }

   /**
   * The ID of the source object (dSource or VDB) to provision from. If this property is not set, the data_source of the snapshot_id will be used.
   * @return sourceDataId
  **/
  @javax.annotation.Nullable
  public String getSourceDataId() {
    return sourceDataId;
  }

  public void setSourceDataId(String sourceDataId) {
    this.sourceDataId = sourceDataId;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvisionVDBBySnapshotDefaultsRequest provisionVDBBySnapshotDefaultsRequest = (ProvisionVDBBySnapshotDefaultsRequest) o;
    return Objects.equals(this.snapshotId, provisionVDBBySnapshotDefaultsRequest.snapshotId) &&
        Objects.equals(this.engineId, provisionVDBBySnapshotDefaultsRequest.engineId) &&
        Objects.equals(this.sourceDataId, provisionVDBBySnapshotDefaultsRequest.sourceDataId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(snapshotId, engineId, sourceDataId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvisionVDBBySnapshotDefaultsRequest {\n");
    sb.append("    snapshotId: ").append(toIndentedString(snapshotId)).append("\n");
    sb.append("    engineId: ").append(toIndentedString(engineId)).append("\n");
    sb.append("    sourceDataId: ").append(toIndentedString(sourceDataId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("snapshot_id");
    openapiFields.add("engine_id");
    openapiFields.add("source_data_id");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ProvisionVDBBySnapshotDefaultsRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ProvisionVDBBySnapshotDefaultsRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ProvisionVDBBySnapshotDefaultsRequest is not found in the empty JSON string", ProvisionVDBBySnapshotDefaultsRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ProvisionVDBBySnapshotDefaultsRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ProvisionVDBBySnapshotDefaultsRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("snapshot_id") != null && !jsonObj.get("snapshot_id").isJsonNull()) && !jsonObj.get("snapshot_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `snapshot_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("snapshot_id").toString()));
      }
      if ((jsonObj.get("engine_id") != null && !jsonObj.get("engine_id").isJsonNull()) && !jsonObj.get("engine_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `engine_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("engine_id").toString()));
      }
      if ((jsonObj.get("source_data_id") != null && !jsonObj.get("source_data_id").isJsonNull()) && !jsonObj.get("source_data_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `source_data_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("source_data_id").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ProvisionVDBBySnapshotDefaultsRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ProvisionVDBBySnapshotDefaultsRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ProvisionVDBBySnapshotDefaultsRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ProvisionVDBBySnapshotDefaultsRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<ProvisionVDBBySnapshotDefaultsRequest>() {
           @Override
           public void write(JsonWriter out, ProvisionVDBBySnapshotDefaultsRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ProvisionVDBBySnapshotDefaultsRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ProvisionVDBBySnapshotDefaultsRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ProvisionVDBBySnapshotDefaultsRequest
  * @throws IOException if the JSON string is invalid with respect to ProvisionVDBBySnapshotDefaultsRequest
  */
  public static ProvisionVDBBySnapshotDefaultsRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ProvisionVDBBySnapshotDefaultsRequest.class);
  }

 /**
  * Convert an instance of ProvisionVDBBySnapshotDefaultsRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

