/*
 * Delphix DCT API
 * Delphix DCT API
 *
 * The version of the OpenAPI document: 3.3.0
 * Contact: support@delphix.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.delphix.dct.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * Represents a time range within a timeflow.
 */
@ApiModel(description = "Represents a time range within a timeflow.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-19T17:08:49.349376+05:30[Asia/Kolkata]")
public class TimeflowRange {
  public static final String SERIALIZED_NAME_START_POINT_LOCATION = "start_point_location";
  @SerializedName(SERIALIZED_NAME_START_POINT_LOCATION)
  private String startPointLocation;

  public static final String SERIALIZED_NAME_START_POINT_TIMESTAMP = "start_point_timestamp";
  @SerializedName(SERIALIZED_NAME_START_POINT_TIMESTAMP)
  private OffsetDateTime startPointTimestamp;

  public static final String SERIALIZED_NAME_END_POINT_LOCATION = "end_point_location";
  @SerializedName(SERIALIZED_NAME_END_POINT_LOCATION)
  private String endPointLocation;

  public static final String SERIALIZED_NAME_END_POINT_TIMESTAMP = "end_point_timestamp";
  @SerializedName(SERIALIZED_NAME_END_POINT_TIMESTAMP)
  private OffsetDateTime endPointTimestamp;

  public static final String SERIALIZED_NAME_TIMEFLOW_ID = "timeflow_id";
  @SerializedName(SERIALIZED_NAME_TIMEFLOW_ID)
  private String timeflowId;

  public static final String SERIALIZED_NAME_PROVISIONABLE = "provisionable";
  @SerializedName(SERIALIZED_NAME_PROVISIONABLE)
  private Boolean provisionable;


  public TimeflowRange startPointLocation(String startPointLocation) {
    
    this.startPointLocation = startPointLocation;
    return this;
  }

   /**
   * The starting location of this range.
   * @return startPointLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1178883", value = "The starting location of this range.")

  public String getStartPointLocation() {
    return startPointLocation;
  }


  public void setStartPointLocation(String startPointLocation) {
    this.startPointLocation = startPointLocation;
  }


  public TimeflowRange startPointTimestamp(OffsetDateTime startPointTimestamp) {
    
    this.startPointTimestamp = startPointTimestamp;
    return this;
  }

   /**
   * The starting timestamp of this range.
   * @return startPointTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-04-01T08:51:34.148Z", value = "The starting timestamp of this range.")

  public OffsetDateTime getStartPointTimestamp() {
    return startPointTimestamp;
  }


  public void setStartPointTimestamp(OffsetDateTime startPointTimestamp) {
    this.startPointTimestamp = startPointTimestamp;
  }


  public TimeflowRange endPointLocation(String endPointLocation) {
    
    this.endPointLocation = endPointLocation;
    return this;
  }

   /**
   * The ending location of this range.
   * @return endPointLocation
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1178884", value = "The ending location of this range.")

  public String getEndPointLocation() {
    return endPointLocation;
  }


  public void setEndPointLocation(String endPointLocation) {
    this.endPointLocation = endPointLocation;
  }


  public TimeflowRange endPointTimestamp(OffsetDateTime endPointTimestamp) {
    
    this.endPointTimestamp = endPointTimestamp;
    return this;
  }

   /**
   * The ending timestamp of this range.
   * @return endPointTimestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2023-04-01T09:51:34.148Z", value = "The ending timestamp of this range.")

  public OffsetDateTime getEndPointTimestamp() {
    return endPointTimestamp;
  }


  public void setEndPointTimestamp(OffsetDateTime endPointTimestamp) {
    this.endPointTimestamp = endPointTimestamp;
  }


  public TimeflowRange timeflowId(String timeflowId) {
    
    this.timeflowId = timeflowId;
    return this;
  }

   /**
   * A reference to the timeflow of this range.
   * @return timeflowId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "timeflow-123", value = "A reference to the timeflow of this range.")

  public String getTimeflowId() {
    return timeflowId;
  }


  public void setTimeflowId(String timeflowId) {
    this.timeflowId = timeflowId;
  }


  public TimeflowRange provisionable(Boolean provisionable) {
    
    this.provisionable = provisionable;
    return this;
  }

   /**
   * Whether or not this range is provisionable.
   * @return provisionable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Whether or not this range is provisionable.")

  public Boolean getProvisionable() {
    return provisionable;
  }


  public void setProvisionable(Boolean provisionable) {
    this.provisionable = provisionable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TimeflowRange timeflowRange = (TimeflowRange) o;
    return Objects.equals(this.startPointLocation, timeflowRange.startPointLocation) &&
        Objects.equals(this.startPointTimestamp, timeflowRange.startPointTimestamp) &&
        Objects.equals(this.endPointLocation, timeflowRange.endPointLocation) &&
        Objects.equals(this.endPointTimestamp, timeflowRange.endPointTimestamp) &&
        Objects.equals(this.timeflowId, timeflowRange.timeflowId) &&
        Objects.equals(this.provisionable, timeflowRange.provisionable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPointLocation, startPointTimestamp, endPointLocation, endPointTimestamp, timeflowId, provisionable);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TimeflowRange {\n");
    sb.append("    startPointLocation: ").append(toIndentedString(startPointLocation)).append("\n");
    sb.append("    startPointTimestamp: ").append(toIndentedString(startPointTimestamp)).append("\n");
    sb.append("    endPointLocation: ").append(toIndentedString(endPointLocation)).append("\n");
    sb.append("    endPointTimestamp: ").append(toIndentedString(endPointTimestamp)).append("\n");
    sb.append("    timeflowId: ").append(toIndentedString(timeflowId)).append("\n");
    sb.append("    provisionable: ").append(toIndentedString(provisionable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

